# -*- mode: ruby -*-

ISO = "bento/ubuntu-20.04"
NET = "192.168.56."
INVENTORY_PATH = "../ansible/inventory"

Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "control",
          :box => ISO,
          :ip => NET + "10",
          :ssh_port => '20010',
          :ssh_vm => "22",
          :ram => 1024,
          :core => 1
        },
        {
          :hostname => "node1",
          :box => ISO,
          :ip => NET + "11",
          :ssh_port => '20011',
          :ssh_vm => "22",
          :ram => 1024,
          :core => 1
        }
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
                vb.name = machine[:hostname]
            end
            node.vm.provision "ansible" do |setup|
              setup.inventory_path = INVENTORY_PATH
              setup.playbook = "../ansible/provision.yml"
              setup.become = true
              setup.extra_vars = { ansible_user: 'vagrant' }
            end
        end
    end
end