apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
