apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: netology-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.84.81
  share: /volume2/nfs
mountOptions:
  - hard
  - nfsvers=4.1